### ISSUE TITLE
How do I build this project?

### ISSUE THREAD

**Issue by Rovanion** [rtslab/EnergyBox#7]
Hi, 
Since there were no instructions provided as to how one builds the project given in the README.md or any other file I went out on a limb and guessed that ant was the build system based on the build.xml. But building the project using ant didn't seem to work:

```
ant
Buildfile: /home/rovanion/source/EnergyBox/build.xml

BUILD FAILED
/home/rovanion/source/EnergyBox/build.xml:8: Cannot find /home/rovanion/source/EnergyBox/nbproject/build-impl.xml imported from /home/rovanion/source/EnergyBox/build.xml

Total time: 0 seconds
```

How do I actually go about building your project?

**Comment by rihards99** [comment]
@ekhve37, we really should merge the PR from @jensgreen before any big changes are made.

**Comment by ekhve37** [comment]
Now that the PR from @jensgreen is merged with my extra fixes, I recommend to use gradle to build EnergyBox as explained in the README file. 

@Rovanion , if you want to add some instructions on how to build it using NetBeans we can add them as another file.

**Comment by Rovanion** [comment]
@ekhve37 I'm an emacs user myself so I'm fine with this.

**Comment by Rovanion** [comment]
Oh, the instructions don't seem to work:

```
$ sudo apt-get install tshark
...
$ LC_ALL=C ./gradlew EnergyBox
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

**Comment by ekhve37** [comment]
I guess you are building it in Linux, right?

It seems an error from the gradle wrapper, so probably @jensgreen can tell you more about it. 

Try otherwise with only gradle EnergyBox.

**Comment by Rovanion** [comment]
Yes, Ubuntu 16.04. Building with gradle directly yields:

```
$ gradle --stacktrace EnergyBox

FAILURE: Build failed with an exception.

* Where:
Build file '/home/rovanion/source/EnergyBox/build.gradle' line: 163

* What went wrong:
A problem occurred evaluating root project 'energybox'.
> Could not find JavaFX Packager Tools, please set one of [jfxrtDir in Gradle Properties, JFXRT_HOME in System Environment, JAVA_HOME in System Environment, java.home in JVM properties]

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'energybox'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:122)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:510)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:90)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: org.gradle.api.GradleException: Could not find JavaFX Packager Tools, please set one of [jfxrtDir in Gradle Properties, JFXRT_HOME in System Environment, JAVA_HOME in System Environment, java.home in JVM properties]
	at build_ciicyjpd2ocbnnp1yw1e7qcu7$_run_closure1$_closure2$_closure3.doCall(/home/rovanion/source/EnergyBox/build.gradle:163)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:159)
	at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated.invokeMethod(Unknown Source)
	at build_ciicyjpd2ocbnnp1yw1e7qcu7$_run_closure1$_closure2$_closure5.doCall(/home/rovanion/source/EnergyBox/build.gradle:187)
	at build_ciicyjpd2ocbnnp1yw1e7qcu7$_run_closure1$_closure2$_closure5.doCall(/home/rovanion/source/EnergyBox/build.gradle)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:159)
	at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated.invokeMethod(Unknown Source)
	at build_ciicyjpd2ocbnnp1yw1e7qcu7$_run_closure1$_closure2.doCall(/home/rovanion/source/EnergyBox/build.gradle:191)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
	at org.gradle.api.internal.initialization.DefaultScriptHandler.dependencies(DefaultScriptHandler.java:54)
	at build_ciicyjpd2ocbnnp1yw1e7qcu7$_run_closure1.doCall(/home/rovanion/source/EnergyBox/build.gradle:134)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
	at org.gradle.api.internal.project.AbstractProject.buildscript(AbstractProject.java:873)
	at org.gradle.api.Project$buildscript.call(Unknown Source)
	at org.gradle.api.internal.project.ProjectScript.buildscript(ProjectScript.groovy:47)
	at org.gradle.api.Script$buildscript.callCurrent(Unknown Source)
	at build_ciicyjpd2ocbnnp1yw1e7qcu7.run(/home/rovanion/source/EnergyBox/build.gradle:133)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 45 more


BUILD FAILED
```

Seems like you've missed to specify some JavaFX system dependency in the README.

**Comment by jensgreen** [comment]
@Rovanion you can try if #12 solves the gradle wrapper issue.

Not sure why it cannot find JavaFX, they should be included in the JDK. Are you running JDK > 8u40? Otherwise maybe some environment variable needs to be set on Linux? 
`Could not find JavaFX Packager Tools, please set one of [jfxrtDir in Gradle Properties, JFXRT_HOME in System Environment, JAVA_HOME in System Environment, java.home in JVM properties]`

**Comment by jensgreen** [comment]
Build is broken on OS X since the fix for the Windows build btw. Looked at it yesterday but didn't have time to fix it. The .class files are not bundled properly.

**Comment by ekhve37** [comment]
Interesting. I just used the same gradle script in addition to copying some files. Please document the progress both for OS X and Linux. Let's see if we find an easy way to build it for the three of them with the gradle scripts. The build still works on my Windows computer.

**Comment by Rovanion** [comment]
@jensgreen With #12 merged and pulled from `master` I got the following error instead:

```
$ LC_ALL=C ./gradlew EnergyBox
Exception in thread "main" java.lang.RuntimeException: Wrapper properties file '/home/rovanion/source/EnergyBox/gradle/wrapper/gradle-wrapper.properties' does not exist.
	at org.gradle.wrapper.WrapperExecutor.forWrapperPropertiesFile(WrapperExecutor.java:45)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:60)
```

About my java version:

```
$ java -showversion
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
OpenJDK Server VM (build 25.91-b14, mixed mode)
```

Both JAVA_HOME and JFXRT_HOME environment variables are empty, but the java executable is of course in PATH.

**Comment by rihards99** [comment]
I have the same problem on Windows 7 so it's not just OS X.

**Comment by ekhve37** [comment]
Have you tried running simple gradle EnergyBox or gradle EnergyBoxWindows without the gradle wrapper? 

I installed gradle, then the latest java for my platform (Windows 7). At least you should get it running @rihards99 , because it works fine for me.

My java version:
java version "1.8.0_92"
Java (TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot (TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Gradle version 2.13.
Groovy 2.4.4. Ant 1.9.6. Gradle is using JVM 1.8.0_91.

**Comment by Rovanion** [comment]
@ekhve37 Yes, see: https://github.com/rtslab/EnergyBox/issues/7#issuecomment-220006749

I would recommend setting up the most basic of automatic testing with Travis CI and some equivalent windows-based tool which, as a first step, only installs and builds the project according to some simple recipe so that you at least know that each subsequent pull request  and push to master actually builds.

**Comment by ekhve37** [comment]
Sorry @Rovanion , the comment was meant for @rihards99. I only have a Windows machine available just now.

**Comment by profitis** [comment]
I tried to download and build the project and I got the same error:

`manos$ ./gradlew EnergyBox
Exception in thread "main" java.lang.RuntimeException: Wrapper properties file '/Users/manos/Documents/workspace/EnergyBox-master/gradle/wrapper/gradle-wrapper.properties' does not exist.
	at org.gradle.wrapper.WrapperExecutor.forWrapperPropertiesFile(WrapperExecutor.java:45)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:60)`

**Comment by jensgreen** [comment]
Seems like it should an easy fix.

I'll try to have a look this weekend. The tool is not very useful if it
doesn't even build after all ☺️

On Wed, Mar 22, 2017, 02:59 profitis <notifications@github.com> wrote:

I tried to download and build the project and I got the same error:

manos$ ./gradlew EnergyBox Exception in thread "main"
java.lang.RuntimeException: Wrapper properties file
'/Users/manos/Documents/workspace/EnergyBox-master/gradle/wrapper/gradle-wrapper.properties'
does not exist. at
org.gradle.wrapper.WrapperExecutor.forWrapperPropertiesFile(WrapperExecutor.java:45)
at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:60)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/rtslab/EnergyBox/issues/7#issuecomment-288275562>, or mute
the thread

**Comment by profitis** [comment]
Many thanks for the quick response :-)

**Comment by jensgreen** [comment]
@profitis if you want, try checking out the PR #16 code and see if that solves your problems

**Comment by profitis** [comment]
It works perfectly ;-) Many many thanks for your immediate fix!

**Comment by jensgreen** [comment]
Awesome 👍  I'll go ahead and close this
